apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotify-credentials
                  key: SPOTIFY_CLIENT_SECRET
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: SPOTIFY_CLIENT_ID
            - name: SPOTIFY_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: SPOTIFY_REDIRECT_URI
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spotify-credentials
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spotify-credentials
                  key: mongodb-passwords
            - name: MONGO_URL
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}/spotify?authSource=spotify"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: spotify-credentials
                  key: SECRET_KEY
